/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as DenunciaRouteImport } from './routes/denuncia'
import { Route as EmpresaRouteImport } from './routes/empresa'
import { Route as FatoresDeRiscoRouteImport } from './routes/fatores-de-risco'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SobreNr01RouteImport } from './routes/sobre-nr01'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAssinarRouteImport } from './routes/admin.assinar'
import { Route as AdminCampanhasRouteImport } from './routes/admin.campanhas'
import { Route as AdminCargosRouteImport } from './routes/admin.cargos'
import { Route as AdminClientesRouteImport } from './routes/admin.clientes'
import { Route as AdminComparativoRouteImport } from './routes/admin.comparativo'
import { Route as AdminDenunciasRouteImport } from './routes/admin.denuncias'
import { Route as AdminEmpresasRouteImport } from './routes/admin.empresas'
import { Route as AdminImportRouteImport } from './routes/admin.import'
import { Route as AdminImportRespostasRouteImport } from './routes/admin.import-respostas'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminMedidasControleRouteImport } from './routes/admin.medidas-controle'
import { Route as AdminPlanosRouteImport } from './routes/admin.planos'
import { Route as AdminQuestionarioRouteImport } from './routes/admin.questionario'
import { Route as AdminRelatorioRouteImport } from './routes/admin.relatorio'
import { Route as AdminSetoresRouteImport } from './routes/admin.setores'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as DenunciaConsultaRouteImport } from './routes/denuncia.consulta'
import { Route as EmpresaIndexRouteImport } from './routes/empresa.index'
import { Route as EmpresaClassificacaoRouteImport } from './routes/empresa.classificacao'
import { Route as EmpresaLoginRouteImport } from './routes/empresa.login'
import { Route as EmpresaPgrRouteImport } from './routes/empresa.pgr'
import { Route as EmpresaRespostasRouteImport } from './routes/empresa.respostas'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'
import { Route as QCodigoIndexRouteImport } from './routes/q.$codigo.index'
import { Route as QCodigoObrigadoRouteImport } from './routes/q.$codigo.obrigado'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const DenunciaRoute = DenunciaRouteImport.update({
  id: '/denuncia',
  path: '/denuncia',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaRoute = EmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const FatoresDeRiscoRoute = FatoresDeRiscoRouteImport.update({
  id: '/fatores-de-risco',
  path: '/fatores-de-risco',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreNr01Route = SobreNr01RouteImport.update({
  id: '/sobre-nr01',
  path: '/sobre-nr01',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssinarRoute = AdminAssinarRouteImport.update({
  id: '/assinar',
  path: '/assinar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCampanhasRoute = AdminCampanhasRouteImport.update({
  id: '/campanhas',
  path: '/campanhas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCargosRoute = AdminCargosRouteImport.update({
  id: '/cargos',
  path: '/cargos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminComparativoRoute = AdminComparativoRouteImport.update({
  id: '/comparativo',
  path: '/comparativo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDenunciasRoute = AdminDenunciasRouteImport.update({
  id: '/denuncias',
  path: '/denuncias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmpresasRoute = AdminEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImportRoute = AdminImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImportRespostasRoute = AdminImportRespostasRouteImport.update({
  id: '/import-respostas',
  path: '/import-respostas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMedidasControleRoute = AdminMedidasControleRouteImport.update({
  id: '/medidas-controle',
  path: '/medidas-controle',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlanosRoute = AdminPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuestionarioRoute = AdminQuestionarioRouteImport.update({
  id: '/questionario',
  path: '/questionario',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRelatorioRoute = AdminRelatorioRouteImport.update({
  id: '/relatorio',
  path: '/relatorio',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSetoresRoute = AdminSetoresRouteImport.update({
  id: '/setores',
  path: '/setores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const DenunciaConsultaRoute = DenunciaConsultaRouteImport.update({
  id: '/consulta',
  path: '/consulta',
  getParentRoute: () => DenunciaRoute,
} as any)
const EmpresaIndexRoute = EmpresaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmpresaRoute,
} as any)
const EmpresaClassificacaoRoute = EmpresaClassificacaoRouteImport.update({
  id: '/classificacao',
  path: '/classificacao',
  getParentRoute: () => EmpresaRoute,
} as any)
const EmpresaLoginRoute = EmpresaLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => EmpresaRoute,
} as any)
const EmpresaPgrRoute = EmpresaPgrRouteImport.update({
  id: '/pgr',
  path: '/pgr',
  getParentRoute: () => EmpresaRoute,
} as any)
const EmpresaRespostasRoute = EmpresaRespostasRouteImport.update({
  id: '/respostas',
  path: '/respostas',
  getParentRoute: () => EmpresaRoute,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const QCodigoIndexRoute = QCodigoIndexRouteImport.update({
  id: '/q/$codigo/',
  path: '/q/$codigo/',
  getParentRoute: () => rootRouteImport,
} as any)
const QCodigoObrigadoRoute = QCodigoObrigadoRouteImport.update({
  id: '/q/$codigo/obrigado',
  path: '/q/$codigo/obrigado',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/como-funciona': typeof ComoFuncionaRoute
  '/contato': typeof ContatoRoute
  '/denuncia': typeof DenunciaRouteWithChildren
  '/empresa': typeof EmpresaRouteWithChildren
  '/fatores-de-risco': typeof FatoresDeRiscoRoute
  '/login': typeof LoginRoute
  '/sobre-nr01': typeof SobreNr01Route
  '/admin/assinar': typeof AdminAssinarRoute
  '/admin/campanhas': typeof AdminCampanhasRoute
  '/admin/cargos': typeof AdminCargosRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/comparativo': typeof AdminComparativoRoute
  '/admin/denuncias': typeof AdminDenunciasRoute
  '/admin/empresas': typeof AdminEmpresasRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/import-respostas': typeof AdminImportRespostasRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/medidas-controle': typeof AdminMedidasControleRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin/questionario': typeof AdminQuestionarioRoute
  '/admin/relatorio': typeof AdminRelatorioRoute
  '/admin/setores': typeof AdminSetoresRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/denuncia/consulta': typeof DenunciaConsultaRoute
  '/empresa/classificacao': typeof EmpresaClassificacaoRoute
  '/empresa/login': typeof EmpresaLoginRoute
  '/empresa/pgr': typeof EmpresaPgrRoute
  '/empresa/respostas': typeof EmpresaRespostasRoute
  '/admin/': typeof AdminIndexRoute
  '/empresa/': typeof EmpresaIndexRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/q/$codigo/obrigado': typeof QCodigoObrigadoRoute
  '/q/$codigo/': typeof QCodigoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contato': typeof ContatoRoute
  '/denuncia': typeof DenunciaRouteWithChildren
  '/fatores-de-risco': typeof FatoresDeRiscoRoute
  '/login': typeof LoginRoute
  '/sobre-nr01': typeof SobreNr01Route
  '/admin/assinar': typeof AdminAssinarRoute
  '/admin/campanhas': typeof AdminCampanhasRoute
  '/admin/cargos': typeof AdminCargosRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/comparativo': typeof AdminComparativoRoute
  '/admin/denuncias': typeof AdminDenunciasRoute
  '/admin/empresas': typeof AdminEmpresasRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/import-respostas': typeof AdminImportRespostasRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/medidas-controle': typeof AdminMedidasControleRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin/questionario': typeof AdminQuestionarioRoute
  '/admin/relatorio': typeof AdminRelatorioRoute
  '/admin/setores': typeof AdminSetoresRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/denuncia/consulta': typeof DenunciaConsultaRoute
  '/empresa/classificacao': typeof EmpresaClassificacaoRoute
  '/empresa/login': typeof EmpresaLoginRoute
  '/empresa/pgr': typeof EmpresaPgrRoute
  '/empresa/respostas': typeof EmpresaRespostasRoute
  '/admin': typeof AdminIndexRoute
  '/empresa': typeof EmpresaIndexRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/q/$codigo/obrigado': typeof QCodigoObrigadoRoute
  '/q/$codigo': typeof QCodigoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/como-funciona': typeof ComoFuncionaRoute
  '/contato': typeof ContatoRoute
  '/denuncia': typeof DenunciaRouteWithChildren
  '/empresa': typeof EmpresaRouteWithChildren
  '/fatores-de-risco': typeof FatoresDeRiscoRoute
  '/login': typeof LoginRoute
  '/sobre-nr01': typeof SobreNr01Route
  '/admin/assinar': typeof AdminAssinarRoute
  '/admin/campanhas': typeof AdminCampanhasRoute
  '/admin/cargos': typeof AdminCargosRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/comparativo': typeof AdminComparativoRoute
  '/admin/denuncias': typeof AdminDenunciasRoute
  '/admin/empresas': typeof AdminEmpresasRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/import-respostas': typeof AdminImportRespostasRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/medidas-controle': typeof AdminMedidasControleRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin/questionario': typeof AdminQuestionarioRoute
  '/admin/relatorio': typeof AdminRelatorioRoute
  '/admin/setores': typeof AdminSetoresRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/denuncia/consulta': typeof DenunciaConsultaRoute
  '/empresa/classificacao': typeof EmpresaClassificacaoRoute
  '/empresa/login': typeof EmpresaLoginRoute
  '/empresa/pgr': typeof EmpresaPgrRoute
  '/empresa/respostas': typeof EmpresaRespostasRoute
  '/admin/': typeof AdminIndexRoute
  '/empresa/': typeof EmpresaIndexRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/q/$codigo/obrigado': typeof QCodigoObrigadoRoute
  '/q/$codigo/': typeof QCodigoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/como-funciona'
    | '/contato'
    | '/denuncia'
    | '/empresa'
    | '/fatores-de-risco'
    | '/login'
    | '/sobre-nr01'
    | '/admin/assinar'
    | '/admin/campanhas'
    | '/admin/cargos'
    | '/admin/clientes'
    | '/admin/comparativo'
    | '/admin/denuncias'
    | '/admin/empresas'
    | '/admin/import'
    | '/admin/import-respostas'
    | '/admin/login'
    | '/admin/medidas-controle'
    | '/admin/planos'
    | '/admin/questionario'
    | '/admin/relatorio'
    | '/admin/setores'
    | '/admin/usuarios'
    | '/denuncia/consulta'
    | '/empresa/classificacao'
    | '/empresa/login'
    | '/empresa/pgr'
    | '/empresa/respostas'
    | '/admin/'
    | '/empresa/'
    | '/api/public/stripe-webhook'
    | '/q/$codigo/obrigado'
    | '/q/$codigo/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/como-funciona'
    | '/contato'
    | '/denuncia'
    | '/fatores-de-risco'
    | '/login'
    | '/sobre-nr01'
    | '/admin/assinar'
    | '/admin/campanhas'
    | '/admin/cargos'
    | '/admin/clientes'
    | '/admin/comparativo'
    | '/admin/denuncias'
    | '/admin/empresas'
    | '/admin/import'
    | '/admin/import-respostas'
    | '/admin/login'
    | '/admin/medidas-controle'
    | '/admin/planos'
    | '/admin/questionario'
    | '/admin/relatorio'
    | '/admin/setores'
    | '/admin/usuarios'
    | '/denuncia/consulta'
    | '/empresa/classificacao'
    | '/empresa/login'
    | '/empresa/pgr'
    | '/empresa/respostas'
    | '/admin'
    | '/empresa'
    | '/api/public/stripe-webhook'
    | '/q/$codigo/obrigado'
    | '/q/$codigo'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/como-funciona'
    | '/contato'
    | '/denuncia'
    | '/empresa'
    | '/fatores-de-risco'
    | '/login'
    | '/sobre-nr01'
    | '/admin/assinar'
    | '/admin/campanhas'
    | '/admin/cargos'
    | '/admin/clientes'
    | '/admin/comparativo'
    | '/admin/denuncias'
    | '/admin/empresas'
    | '/admin/import'
    | '/admin/import-respostas'
    | '/admin/login'
    | '/admin/medidas-controle'
    | '/admin/planos'
    | '/admin/questionario'
    | '/admin/relatorio'
    | '/admin/setores'
    | '/admin/usuarios'
    | '/denuncia/consulta'
    | '/empresa/classificacao'
    | '/empresa/login'
    | '/empresa/pgr'
    | '/empresa/respostas'
    | '/admin/'
    | '/empresa/'
    | '/api/public/stripe-webhook'
    | '/q/$codigo/obrigado'
    | '/q/$codigo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  ContatoRoute: typeof ContatoRoute
  DenunciaRoute: typeof DenunciaRouteWithChildren
  EmpresaRoute: typeof EmpresaRouteWithChildren
  FatoresDeRiscoRoute: typeof FatoresDeRiscoRoute
  LoginRoute: typeof LoginRoute
  SobreNr01Route: typeof SobreNr01Route
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
  QCodigoObrigadoRoute: typeof QCodigoObrigadoRoute
  QCodigoIndexRoute: typeof QCodigoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/denuncia': {
      id: '/denuncia'
      path: '/denuncia'
      fullPath: '/denuncia'
      preLoaderRoute: typeof DenunciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa': {
      id: '/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof EmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fatores-de-risco': {
      id: '/fatores-de-risco'
      path: '/fatores-de-risco'
      fullPath: '/fatores-de-risco'
      preLoaderRoute: typeof FatoresDeRiscoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre-nr01': {
      id: '/sobre-nr01'
      path: '/sobre-nr01'
      fullPath: '/sobre-nr01'
      preLoaderRoute: typeof SobreNr01RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assinar': {
      id: '/admin/assinar'
      path: '/assinar'
      fullPath: '/admin/assinar'
      preLoaderRoute: typeof AdminAssinarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/campanhas': {
      id: '/admin/campanhas'
      path: '/campanhas'
      fullPath: '/admin/campanhas'
      preLoaderRoute: typeof AdminCampanhasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cargos': {
      id: '/admin/cargos'
      path: '/cargos'
      fullPath: '/admin/cargos'
      preLoaderRoute: typeof AdminCargosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/comparativo': {
      id: '/admin/comparativo'
      path: '/comparativo'
      fullPath: '/admin/comparativo'
      preLoaderRoute: typeof AdminComparativoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/denuncias': {
      id: '/admin/denuncias'
      path: '/denuncias'
      fullPath: '/admin/denuncias'
      preLoaderRoute: typeof AdminDenunciasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/empresas': {
      id: '/admin/empresas'
      path: '/empresas'
      fullPath: '/admin/empresas'
      preLoaderRoute: typeof AdminEmpresasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/import': {
      id: '/admin/import'
      path: '/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AdminImportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/import-respostas': {
      id: '/admin/import-respostas'
      path: '/import-respostas'
      fullPath: '/admin/import-respostas'
      preLoaderRoute: typeof AdminImportRespostasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/medidas-controle': {
      id: '/admin/medidas-controle'
      path: '/medidas-controle'
      fullPath: '/admin/medidas-controle'
      preLoaderRoute: typeof AdminMedidasControleRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/planos': {
      id: '/admin/planos'
      path: '/planos'
      fullPath: '/admin/planos'
      preLoaderRoute: typeof AdminPlanosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/questionario': {
      id: '/admin/questionario'
      path: '/questionario'
      fullPath: '/admin/questionario'
      preLoaderRoute: typeof AdminQuestionarioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/relatorio': {
      id: '/admin/relatorio'
      path: '/relatorio'
      fullPath: '/admin/relatorio'
      preLoaderRoute: typeof AdminRelatorioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/setores': {
      id: '/admin/setores'
      path: '/setores'
      fullPath: '/admin/setores'
      preLoaderRoute: typeof AdminSetoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/denuncia/consulta': {
      id: '/denuncia/consulta'
      path: '/consulta'
      fullPath: '/denuncia/consulta'
      preLoaderRoute: typeof DenunciaConsultaRouteImport
      parentRoute: typeof DenunciaRoute
    }
    '/empresa/': {
      id: '/empresa/'
      path: '/'
      fullPath: '/empresa/'
      preLoaderRoute: typeof EmpresaIndexRouteImport
      parentRoute: typeof EmpresaRoute
    }
    '/empresa/classificacao': {
      id: '/empresa/classificacao'
      path: '/classificacao'
      fullPath: '/empresa/classificacao'
      preLoaderRoute: typeof EmpresaClassificacaoRouteImport
      parentRoute: typeof EmpresaRoute
    }
    '/empresa/login': {
      id: '/empresa/login'
      path: '/login'
      fullPath: '/empresa/login'
      preLoaderRoute: typeof EmpresaLoginRouteImport
      parentRoute: typeof EmpresaRoute
    }
    '/empresa/pgr': {
      id: '/empresa/pgr'
      path: '/pgr'
      fullPath: '/empresa/pgr'
      preLoaderRoute: typeof EmpresaPgrRouteImport
      parentRoute: typeof EmpresaRoute
    }
    '/empresa/respostas': {
      id: '/empresa/respostas'
      path: '/respostas'
      fullPath: '/empresa/respostas'
      preLoaderRoute: typeof EmpresaRespostasRouteImport
      parentRoute: typeof EmpresaRoute
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/q/$codigo/': {
      id: '/q/$codigo/'
      path: '/q/$codigo'
      fullPath: '/q/$codigo/'
      preLoaderRoute: typeof QCodigoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/q/$codigo/obrigado': {
      id: '/q/$codigo/obrigado'
      path: '/q/$codigo/obrigado'
      fullPath: '/q/$codigo/obrigado'
      preLoaderRoute: typeof QCodigoObrigadoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAssinarRoute: typeof AdminAssinarRoute
  AdminCampanhasRoute: typeof AdminCampanhasRoute
  AdminCargosRoute: typeof AdminCargosRoute
  AdminClientesRoute: typeof AdminClientesRoute
  AdminComparativoRoute: typeof AdminComparativoRoute
  AdminDenunciasRoute: typeof AdminDenunciasRoute
  AdminEmpresasRoute: typeof AdminEmpresasRoute
  AdminImportRoute: typeof AdminImportRoute
  AdminImportRespostasRoute: typeof AdminImportRespostasRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMedidasControleRoute: typeof AdminMedidasControleRoute
  AdminPlanosRoute: typeof AdminPlanosRoute
  AdminQuestionarioRoute: typeof AdminQuestionarioRoute
  AdminRelatorioRoute: typeof AdminRelatorioRoute
  AdminSetoresRoute: typeof AdminSetoresRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAssinarRoute: AdminAssinarRoute,
  AdminCampanhasRoute: AdminCampanhasRoute,
  AdminCargosRoute: AdminCargosRoute,
  AdminClientesRoute: AdminClientesRoute,
  AdminComparativoRoute: AdminComparativoRoute,
  AdminDenunciasRoute: AdminDenunciasRoute,
  AdminEmpresasRoute: AdminEmpresasRoute,
  AdminImportRoute: AdminImportRoute,
  AdminImportRespostasRoute: AdminImportRespostasRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMedidasControleRoute: AdminMedidasControleRoute,
  AdminPlanosRoute: AdminPlanosRoute,
  AdminQuestionarioRoute: AdminQuestionarioRoute,
  AdminRelatorioRoute: AdminRelatorioRoute,
  AdminSetoresRoute: AdminSetoresRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DenunciaRouteChildren {
  DenunciaConsultaRoute: typeof DenunciaConsultaRoute
}

const DenunciaRouteChildren: DenunciaRouteChildren = {
  DenunciaConsultaRoute: DenunciaConsultaRoute,
}

const DenunciaRouteWithChildren = DenunciaRoute._addFileChildren(
  DenunciaRouteChildren,
)

interface EmpresaRouteChildren {
  EmpresaClassificacaoRoute: typeof EmpresaClassificacaoRoute
  EmpresaLoginRoute: typeof EmpresaLoginRoute
  EmpresaPgrRoute: typeof EmpresaPgrRoute
  EmpresaRespostasRoute: typeof EmpresaRespostasRoute
  EmpresaIndexRoute: typeof EmpresaIndexRoute
}

const EmpresaRouteChildren: EmpresaRouteChildren = {
  EmpresaClassificacaoRoute: EmpresaClassificacaoRoute,
  EmpresaLoginRoute: EmpresaLoginRoute,
  EmpresaPgrRoute: EmpresaPgrRoute,
  EmpresaRespostasRoute: EmpresaRespostasRoute,
  EmpresaIndexRoute: EmpresaIndexRoute,
}

const EmpresaRouteWithChildren =
  EmpresaRoute._addFileChildren(EmpresaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ComoFuncionaRoute: ComoFuncionaRoute,
  ContatoRoute: ContatoRoute,
  DenunciaRoute: DenunciaRouteWithChildren,
  EmpresaRoute: EmpresaRouteWithChildren,
  FatoresDeRiscoRoute: FatoresDeRiscoRoute,
  LoginRoute: LoginRoute,
  SobreNr01Route: SobreNr01Route,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
  QCodigoObrigadoRoute: QCodigoObrigadoRoute,
  QCodigoIndexRoute: QCodigoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
